language: cpp

sudo: false

compiler:
    - gcc
before_install:
    - git submodule update --init --recursive
    - git submodule update --recursive
    - cd geojs
    - npm install
    - grunt library
    - cd ..

install:
    - curl https://raw.githubusercontent.com/draperlaboratory/user-ale/master/helper-libs/javascript/draper.activity_logger-2.1.1.js -o client/optional/js/draper.activity_logger-2.1.1.js
    - curl https://raw.githubusercontent.com/draperlaboratory/user-ale/master/helper-libs/javascript/draper.activity_worker-2.1.1.js -o client/optional/static/draper.activity_worker-2.1.1.js
    
    - npm install

    - mkdir env
    - cd env
    - pip install --user girder python-dateutil PyGreSQL==4.1.1 psycopg2
    - python -c "import bcrypt"
    - ~/.local/bin/girder-install web
    - ~/.local/bin/girder-install plugin

script:
    - python ../server/main.py &
    - curl --silent 'http://localhost:8001/api/v1/system/version' | grep -q 'apiVersion'
