language: cpp

sudo: false

compiler:
    - gcc
before_install:
    - pushd "${HOME}"
    - curl "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.1.tgz" | gunzip -c | tar x
    - cd mongodb-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - mkdir /tmp/db
    - mongod --dbpath=/tmp/db >/dev/null 2>/dev/null &
    - mongod --version

    - pushd "${HOME}"
    - curl "http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz" | gunzip -c | tar x
    - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
    - popd
    - cmake --version

    - git submodule update --init --recursive
    - git submodule update --recursive
    - cd geojs
    - npm install
    - grunt library
    - cd ..

install:
    - curl https://raw.githubusercontent.com/draperlaboratory/user-ale/master/helper-libs/javascript/userale.js -o client/optional/js/userale.js
    - curl https://raw.githubusercontent.com/draperlaboratory/user-ale/master/helper-libs/javascript/userale-worker.js -o client/optional/static/userale-worker.js
    
    - npm install

    - mkdir env
    - cd env
    - pip install --user -r requirements.txt -r requirements-dev.txt
    - ~/.local/bin/girder-install web
    - PIP_USER=yes ~/.local/bin/girder-install plugin

script:
    # Run ctest
    - cd ..
    - mkdir _build
    - cd _build
    - cmake ..
    - ctest -VV -j 3
    - if [ -f test_failed ] ; then false ; fi

    # Make sure we can query a REST end point
    - cd ../server
    - python -c "import cherrypy,sys,urllib,main as geoapp;app=geoapp.GeoApp();app.start(False);test = 'apiVersion' in urllib.urlopen('http://localhost:8001/api/v1/system/version').read();cherrypy.engine.exit();sys.exit(0 if test else 1)"
