Vagrant.configure("2") do |config|
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.box = "ubuntu/trusty_64"
  # The exposed ports can be changed here; the ssh port is never necessary.
  config.vm.network "forwarded_port", guest: 22, host: 2210
  config.vm.network "forwarded_port", guest: 8080, host: 8010
  config.vm.network "forwarded_port", guest: 27017, host: 27010
  config.vm.provider "virtualbox" do |v|
    v.name = "D2D Demo"
    # You may need to configure this to run benignly on your host machine
    v.memory = 4096
    v.cpus = 4
    # Size the disk to a specific number of Mbytes.
    # v.customize ["modifyhd", ":id", "--resize", "102400"]
  end

  $script = <<SCRIPT
if [ -f ~/vagrant_provisioned_date ]; then
    echo Already provisioned.
else 

echo Starting provisioning.

cd /vagrant
/bin/bash provision.sh

# Record that we provisioned
date > ~/vagrant_provisioned_date
echo Done provisioning.

fi
SCRIPT
  config.vm.provision "shell", inline: $script

end
